var allQuestions = [
  {
    id: 1,
    question: "Which part of speech names a person, place, or thing?",
    option1: "noun",
    option2: "adjective",
    option3: "preposition",
    option4: "verb",
    answer: 1,
  },
  {
    id: 2,
    question: "Which part of speech replaces a noun?",
    option1: "conjunction",
    option2: "adverb",
    option3: "pronoun",
    option4: "preposition",
    answer: 3,
  },
  {
    id: 3,
    question: "Which part of speech describes a noun or a pronoun?",
    option1: "adjective",
    option2: "adverb",
    option3: "conjunction",
    option4: "verb",
    answer: 1,
  },
  {
    id: 4,
    question: "Which part of speech modifies a verb, adjective, or adverb?",
    option1: "preposition",
    option2: "verb",
    option3: "noun",
    option4: "adverb",
    answer: 4,
  },
  {
    id: 5,
    question: "Define:  Verb",
    option1: "An action",
    option2: "A word that gives more detail about nouns",
    option3: "A person, place, thing, or idea",
    option4: "A word that gives more details about verbs",
    answer: 1,
  },
];
